spring.application.name=sports-club

spring.datasource.url=jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:sports_club}
spring.datasource.username=${DB_USER:sportsteam}
spring.datasource.password=${DB_PASSWORD:sportsteam}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
